---
version: 2
jobs:
    build:
        working_directory: ~/hello_app
        docker:
            - image: circleci/ruby:2.4.1-browsers
            environment:
                RAILS_ENV: test
    steps:
        - checkout

        # Setup the environment
      - run: cp .sample.env .env

      # Run the tests
      - run: bundle exec rake